global using System.Collections.Concurrent;
global using System.Diagnostics;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Text;
global using System.Text.RegularExpressions;
global using System.Xml;
global using FluentAssertions;
global using Markdig;
global using Markdig.Syntax;
global using Markdig.Syntax.Inlines;
global using NetArchTest.Rules;
global using Xunit;
global using Xunit.Abstractions;
global using Zss.BilliardHall.Platform.Exceptions;
global using Zss.BilliardHall.Tests.ArchitectureTests.Shared;
global using static Zss.BilliardHall.Tests.ArchitectureTests.Shared.AssertionMessageBuilder;
