using Zss.BilliardHall.Generators;
using Zss.BilliardHall.Tools.Governance.Cli.Commands;
using Zss.BilliardHall.Tools.Governance.Cli.Infrastructure;
using Zss.BilliardHall.Tools.Governance.Cli.Tests.Infrastructure;

namespace Zss.BilliardHall.Tools.Governance.Cli.Tests.Commands;

public sealed class GenerateTestCommandHandlerTests
{
    [Fact]
    public async Task ExecuteAsync_ShouldGenerateTestFile()
    {
        // Arrange
        var fileSystem = new InMemoryFileSystem();
        const string outputDir = "/output";
        fileSystem.CreateDirectory(outputDir);

        var testGenerator = new ArchitectureTestGenerator();
        var pathValidator = new NoOpPathValidator();
        var handler = new GenerateTestCommandHandler(fileSystem, testGenerator, pathValidator);

        // Act
        var exitCode = await handler.ExecuteAsync(outputDir, adrNumber: 1);

        // Assert
        exitCode.Should().Be(0);
        var files = fileSystem.GetAllFiles();
        files.Should().ContainKey("/output/Adr001AutoGenerated_Tests.cs");
    }

    [Fact]
    public async Task ExecuteAsync_WithoutAdrNumber_ShouldGenerateMultipleFiles()
    {
        // Arrange
        var fileSystem = new InMemoryFileSystem();
        const string outputDir = "/output";
        fileSystem.CreateDirectory(outputDir);

        var testGenerator = new ArchitectureTestGenerator();
        var pathValidator = new NoOpPathValidator();
        var handler = new GenerateTestCommandHandler(fileSystem, testGenerator, pathValidator);

        // Act
        var exitCode = await handler.ExecuteAsync(outputDir, adrNumber: null);

        // Assert
        exitCode.Should().Be(0);
        var files = fileSystem.GetAllFiles();
        files.Should().NotBeEmpty();
        // 断言文件名符合预期格式：Adr{number:D3}AutoGenerated_Tests.cs
        files.Keys.Should().Contain(key => key.Contains("Adr") && key.EndsWith("AutoGenerated_Tests.cs"));
    }

    [Fact]
    public async Task ExecuteAsync_WithNonExistentDirectory_ShouldCreateIt()
    {
        // Arrange
        var fileSystem = new InMemoryFileSystem();
        const string outputDir = "/new/output";

        var testGenerator = new ArchitectureTestGenerator();
        var pathValidator = new NoOpPathValidator();
        var handler = new GenerateTestCommandHandler(fileSystem, testGenerator, pathValidator);

        // Act
        var exitCode = await handler.ExecuteAsync(outputDir, adrNumber: 1);

        // Assert
        exitCode.Should().Be(0);
        fileSystem.DirectoryExists(outputDir).Should().BeTrue();
    }

    [Fact]
    public async Task ExecuteAsync_ShouldValidateOutputPathSafety()
    {
        // Arrange
        var fileSystem = new InMemoryFileSystem();
        const string unsafePath = "/unsafe/path";

        var testGenerator = new ArchitectureTestGenerator();
        // 使用 FakePathValidator 拒绝特定路径，避免依赖真实文件系统
        var pathValidator = FakePathValidator.RejectPath(unsafePath, "路径不在仓库根目录下");
        var handler = new GenerateTestCommandHandler(fileSystem, testGenerator, pathValidator);

        // Act
        var exitCode = await handler.ExecuteAsync(unsafePath, adrNumber: 1);

        // Assert
        exitCode.Should().Be(1);
        var files = fileSystem.GetAllFiles();
        files.Should().BeEmpty();
    }
}
