namespace Zss.BilliardHall.Generators;
using Zss.BilliardHall.Specification.Rules;

/// <summary>
/// 架构测试生成器实现（协调器模式）
/// 将 RuleSet 转换为 xUnit 测试代码
/// 
/// 职责：
/// - 协调生成流程：Validate → BuildModel → Render → PostProcess
/// - 依赖注入的组件：TemplateRenderer、ClauseExecutorFactory
/// - 保持接口签名不变，确保向后兼容
/// 
/// 生成策略：
/// 1. 使用 Theory + MemberData 模式（参考 ADR907 Auto_Tests）
/// 2. 为每个 Clause 生成测试数据
/// 3. 生成命名符合 ADR-XXX_Rule_Clause 规范的方法
/// 4. 使用策略模式处理不同 ExecutionType
/// 5. 统一行尾为 LF
/// </summary>
public sealed class ArchitectureTestGenerator : IArchitectureTestGenerator
{
    private readonly TemplateRenderer _renderer;

    /// <summary>
    /// 构造函数
    /// </summary>
    public ArchitectureTestGenerator()
    {
        var factory = new ClauseExecutorFactory();
        _renderer = new TemplateRenderer(factory);
    }

    /// <summary>
    /// 构造函数（支持依赖注入）
    /// </summary>
    /// <param name="renderer">模板渲染器</param>
    internal ArchitectureTestGenerator(TemplateRenderer renderer)
    {
        _renderer = Guard.NotNull(renderer, nameof(renderer));
    }

    /// <summary>
    /// 生成架构测试代码
    /// </summary>
    public GeneratedTestCode Generate(ArchitectureRuleSet ruleSet, TestGenerationOptions? options = null)
    {
        // 阶段 1：验证输入
        Guard.NotNull(ruleSet, nameof(ruleSet));
        options ??= TestGenerationOptions.Default;

        // 验证 RuleSet 完整性
        ruleSet.ValidateCompleteness();

        // 阶段 2：构建模型
        var className = BuildClassName(ruleSet.AdrNumber, options);
        var namespaceName = options.Namespace;

        // 阶段 3：渲染代码
        var sourceCode = _renderer.RenderTestClass(ruleSet, className, namespaceName, options);

        // 阶段 4：后处理与验证
        var testMethodCount = CalculateTestMethodCount(ruleSet, options);
        var result = new GeneratedTestCode(className, sourceCode, namespaceName, testMethodCount);
        result.Validate();

        return result;
    }

    /// <summary>
    /// 构建测试类名
    /// </summary>
    private string BuildClassName(int adrNumber, TestGenerationOptions options)
    {
        return $"Adr{adrNumber:D3}AutoGenerated{options.TestClassSuffix}";
    }

    /// <summary>
    /// 计算测试方法数量
    /// </summary>
    private int CalculateTestMethodCount(ArchitectureRuleSet ruleSet, TestGenerationOptions options)
    {
        return options.UseTheoryPattern ? 1 : ruleSet.ClauseCount;
    }
}
