instructions:
  - id: DE-001
    description: "分析 .NET 代码架构，保证 Handler 与模块边界符合 ADR"
    action: "静态分析代码"
    conditions:
      - "Push to src/"
      - "PullRequest"
    output: "Pass / Fail"
    tools:
      - "Roslyn Analyzer"
      - "ArchitectureTests"
    feedback:
      - "报告违反 ADR-240 / ADR-007 Clause"
