instructions:
  - id: TG-001
    description: "根据 ADR Clause 自动生成 Architecture Tests"
    action: "生成对应测试方法"
    conditions:
      - "PullRequest"
      - "New ADR Added"
    output: "Generated Tests"
    tools:
      - "ArchitectureTests"
      - "Codegen Templates"
    feedback:
      - "提交生成测试至测试项目"

  - id: TG-002
    description: "遵循架构测试编写指南生成测试"
    action: "在生成测试时严格应用 ARCHITECTURE-TEST-GUIDELINES.md 中的规范"
    conditions:
      - "All Test Generation Tasks"
    output: "Compliant Architecture Tests"
    tools:
      - "ARCHITECTURE-TEST-GUIDELINES.md"
      - "Shared/TestEnvironment.cs"
    feedback:
      - "确保测试类使用 sealed 关键字"
      - "避免重复代码，使用 Shared/TestEnvironment.cs"
      - "断言消息包含详细违规描述、当前状态和修复建议"
      - "文档注释完整，包括 ADR 条款引用"
