using Zss.BilliardHall.Generators;

namespace Zss.BilliardHall.Tests.ArchitectureTests.Specification.Generation;

/// <summary>
/// ArchitectureTestGenerator 单元测试
/// </summary>
public sealed class ArchitectureTestGenerator_Tests
{
    private readonly IArchitectureTestGenerator _generator;

    public ArchitectureTestGenerator_Tests()
    {
        _generator = new ArchitectureTestGenerator();
    }

    [Fact(DisplayName = "Generate 应该对 null RuleSet 抛出异常")]
    public void Generate_Should_Throw_For_Null_RuleSet()
    {
        // Act & Assert
        Assert.Throws<ArgumentNullException>(() => _generator.Generate(null!));
    }

    [Fact(DisplayName = "Generate 应该生成有效的测试代码")]
    public void Generate_Should_Generate_Valid_Test_Code()
    {
        // Arrange
        var ruleSet = CreateTestRuleSet();

        // Act
        var result = _generator.Generate(ruleSet);

        // Assert
        result.Should().NotBeNull();
        result.ClassName.Should().Be("Adr999AutoGenerated_Tests");
        result.Namespace.Should().Be("Zss.BilliardHall.Tests.ArchitectureTests.Generated");
        result.TestMethodCount.Should().Be(1); // Theory 模式只有1个方法
        result.SourceCode.Should().NotBeNullOrEmpty();
    }

    [Fact(DisplayName = "Generate 应该包含命名空间声明")]
    public void Generate_Should_Include_Namespace_Declaration()
    {
        // Arrange
        var ruleSet = CreateTestRuleSet();

        // Act
        var result = _generator.Generate(ruleSet);

        // Assert
        result.SourceCode.Should().Contain("namespace Zss.BilliardHall.Tests.ArchitectureTests.Generated;");
    }

    [Fact(DisplayName = "Generate 应该包含测试类声明")]
    public void Generate_Should_Include_Test_Class_Declaration()
    {
        // Arrange
        var ruleSet = CreateTestRuleSet();

        // Act
        var result = _generator.Generate(ruleSet);

        // Assert
        result.SourceCode.Should().Contain("public sealed class Adr999AutoGenerated_Tests");
    }

    [Fact(DisplayName = "Generate 应该包含测试数据提供器")]
    public void Generate_Should_Include_Test_Data_Provider()
    {
        // Arrange
        var ruleSet = CreateTestRuleSet();

        // Act
        var result = _generator.Generate(ruleSet);

        // Assert
        result.SourceCode.Should().Contain("public static IEnumerable<object[]> GetAllClausesData()");
        result.SourceCode.Should().Contain("yield return");
    }

    [Fact(DisplayName = "Generate 应该包含 Theory 测试方法")]
    public void Generate_Should_Include_Theory_Test_Method()
    {
        // Arrange
        var ruleSet = CreateTestRuleSet();

        // Act
        var result = _generator.Generate(ruleSet);

        // Assert
        result.SourceCode.Should().Contain("[Theory(DisplayName = \"ADR-999 条款执行测试\")]");
        result.SourceCode.Should().Contain("[MemberData(nameof(GetAllClausesData))]");
        result.SourceCode.Should().Contain("public void ExecuteClause(int ruleId, int clauseId, string safeName, string displayName)");
    }

    [Fact(DisplayName = "Generate 应该包含示例实现")]
    public void Generate_Should_Include_Example_Implementation()
    {
        // Arrange
        var ruleSet = CreateTestRuleSet();
        var options = new TestGenerationOptions { IncludeExampleImplementation = true };

        // Act
        var result = _generator.Generate(ruleSet, options);

        // Assert
        result.SourceCode.Should().Contain("var ruleSet = RuleSetRegistry.GetStrict(999);");
        result.SourceCode.Should().Contain("var clause = ruleSet.GetClause(ruleId, clauseId);");
        result.SourceCode.Should().Contain("switch (clause!.ExecutionType)");
    }

    [Fact(DisplayName = "Generate 应该支持自定义命名空间")]
    public void Generate_Should_Support_Custom_Namespace()
    {
        // Arrange
        var ruleSet = CreateTestRuleSet();
        var options = new TestGenerationOptions { Namespace = "Custom.Test.Namespace" };

        // Act
        var result = _generator.Generate(ruleSet, options);

        // Assert
        result.Namespace.Should().Be("Custom.Test.Namespace");
        result.SourceCode.Should().Contain("namespace Custom.Test.Namespace;");
    }

    [Fact(DisplayName = "Generate 应该支持自定义测试类后缀")]
    public void Generate_Should_Support_Custom_Test_Class_Suffix()
    {
        // Arrange
        var ruleSet = CreateTestRuleSet();
        var options = new TestGenerationOptions { TestClassSuffix = "_ArchTests" };

        // Act
        var result = _generator.Generate(ruleSet, options);

        // Assert
        result.ClassName.Should().Be("Adr999AutoGenerated_ArchTests");
        result.SourceCode.Should().Contain("public sealed class Adr999AutoGenerated_ArchTests");
    }

    [Fact(DisplayName = "Generate 应该规范化行尾")]
    public void Generate_Should_Normalize_Line_Endings()
    {
        // Arrange
        var ruleSet = CreateTestRuleSet();

        // Act
        var result = _generator.Generate(ruleSet);

        // Assert
        result.SourceCode.Should().NotContain("\r\n");
        result.SourceCode.Should().NotContain("\r");
    }

    [Fact(DisplayName = "Generate 应该包含类文档注释")]
    public void Generate_Should_Include_Class_Documentation()
    {
        // Arrange
        var ruleSet = CreateTestRuleSet();
        var options = new TestGenerationOptions { IncludeComments = true };

        // Act
        var result = _generator.Generate(ruleSet, options);

        // Assert
        result.SourceCode.Should().Contain("/// <summary>");
        result.SourceCode.Should().Contain("/// ADR-999 自动生成架构测试");
        result.SourceCode.Should().Contain("/// </summary>");
    }

    [Fact(DisplayName = "Generate 应该为每个条款生成测试数据")]
    public void Generate_Should_Generate_Test_Data_For_Each_Clause()
    {
        // Arrange
        var ruleSet = CreateTestRuleSet();

        // Act
        var result = _generator.Generate(ruleSet);

        // Assert
        // 应该包含2个条款的数据
        var yieldCount = Regex.Matches(result.SourceCode, @"yield return").Count;
        yieldCount.Should().Be(2);
    }

    [Fact(DisplayName = "Generate 不包含示例实现时应该有 TODO 注释")]
    public void Generate_Without_Example_Implementation_Should_Have_TODO()
    {
        // Arrange
        var ruleSet = CreateTestRuleSet();
        var options = new TestGenerationOptions { IncludeExampleImplementation = false };

        // Act
        var result = _generator.Generate(ruleSet, options);

        // Assert
        result.SourceCode.Should().Contain("// TODO: 实现具体的测试逻辑");
        result.SourceCode.Should().Contain("throw new NotImplementedException");
    }

    [Fact(DisplayName = "Generate 应该验证 RuleSet 完整性")]
    public void Generate_Should_Validate_RuleSet_Completeness()
    {
        // Arrange - 创建没有条款的规则集
        var ruleSet = new ArchitectureRuleSet(999);
        ruleSet.AddRule(1, "测试规则", DecisionLevel.Must, RuleSeverity.Governance, RuleScope.Test);

        // Act & Assert
        Assert.Throws<InvalidOperationException>(() => _generator.Generate(ruleSet));
    }

    private ArchitectureRuleSet CreateTestRuleSet()
    {
        var ruleSet = new ArchitectureRuleSet(999);

        ruleSet.AddRule(
            1,
            "测试规则",
            DecisionLevel.Must,
            RuleSeverity.Governance,
            RuleScope.Test);

        ruleSet.AddClause(
            1,
            1,
            "测试条件1",
            "测试执行要求1",
            ClauseExecutionType.Convention);

        ruleSet.AddClause(
            1,
            2,
            "测试条件2",
            "测试执行要求2",
            ClauseExecutionType.StaticAnalysis);

        return ruleSet;
    }
}
