namespace Zss.BilliardHall.Tests.ArchitectureTests.Specification.Generation;

/// <summary>
/// 架构测试生成器实现
/// 将 RuleSet 转换为 xUnit 测试代码
/// 
/// 生成策略：
/// 1. 使用 Theory + MemberData 模式（参考 ADR907 Auto_Tests）
/// 2. 为每个 Clause 生成测试数据
/// 3. 生成命名符合 ADR-XXX_Rule_Clause 规范的方法
/// 4. 包含 NetArchTest 断言示例
/// 5. 提供可扩展的执行绑定点
/// </summary>
public sealed class ArchitectureTestGenerator : IArchitectureTestGenerator
{
    /// <summary>
    /// 生成架构测试代码
    /// </summary>
    public GeneratedTestCode Generate(ArchitectureRuleSet ruleSet, TestGenerationOptions? options = null)
    {
        if (ruleSet == null)
        {
            throw new ArgumentNullException(nameof(ruleSet));
        }

        options ??= TestGenerationOptions.Default;

        // 验证 RuleSet 完整性
        ruleSet.ValidateCompleteness();

        // 生成测试类名
        var className = GenerateClassName(ruleSet.AdrNumber, options);

        // 生成命名空间
        var ns = options.Namespace;

        // 生成源代码
        var sourceCode = GenerateSourceCode(ruleSet, className, ns, options);

        // 计算生成的测试方法数量
        var testMethodCount = options.UseTheoryPattern ? 1 : ruleSet.ClauseCount;

        var result = new GeneratedTestCode(className, sourceCode, ns, testMethodCount);
        result.Validate();

        return result;
    }

    private string GenerateClassName(int adrNumber, TestGenerationOptions options)
    {
        return $"Adr{adrNumber:D3}AutoGenerated{options.TestClassSuffix}";
    }

    private string GenerateSourceCode(
        ArchitectureRuleSet ruleSet,
        string className,
        string ns,
        TestGenerationOptions options)
    {
        var parts = new List<string>();

        // 命名空间声明
        parts.Add(CodeGenerationHelper.BuildNamespaceDeclaration(ns));
        parts.Add("");

        // 类文档注释
        if (options.IncludeComments)
        {
            parts.Add(GenerateClassDocComment(ruleSet));
        }

        // 类声明
        parts.Add($"public sealed class {className}");
        parts.Add("{");

        // 生成测试数据提供器方法
        parts.Add(GenerateTestDataProvider(ruleSet, options));
        parts.Add("");

        // 生成测试方法
        if (options.UseTheoryPattern)
        {
            parts.Add(GenerateTheoryTestMethod(ruleSet, options));
        }
        else
        {
            parts.Add(GenerateFactTestMethods(ruleSet, options));
        }

        // 类结束
        parts.Add("}");

        return CodeGenerationHelper.NormalizeNewlines(string.Join("\n", parts));
    }

    private string GenerateClassDocComment(ArchitectureRuleSet ruleSet)
    {
        var lines = new[]
        {
            $"ADR-{ruleSet.AdrNumber:D3} 自动生成架构测试",
            "此文件由 ArchitectureTestGenerator 自动生成",
            "",
            $"包含 {ruleSet.RuleCount} 个规则，{ruleSet.ClauseCount} 个条款",
            "",
            "使用说明：",
            "1. 此测试使用 Theory + MemberData 模式",
            "2. 每个 Clause 对应一个测试数据项",
            "3. 可在测试方法中添加具体的 NetArchTest 断言",
            "4. 建议结合 ExecutionBindings 实现具体验证逻辑"
        };

        return CodeGenerationHelper.BuildXmlDocCommentMultiLine(lines, 1);
    }

    private string GenerateTestDataProvider(ArchitectureRuleSet ruleSet, TestGenerationOptions options)
    {
        var indent = options.IndentString;
        var parts = new List<string>();

        if (options.IncludeComments)
        {
            parts.Add($"{indent}/// <summary>");
            parts.Add($"{indent}/// 提供所有条款的测试数据");
            parts.Add($"{indent}/// </summary>");
        }

        parts.Add($"{indent}public static IEnumerable<object[]> GetAllClausesData()");
        parts.Add($"{indent}{{");

        // 生成每个条款的数据
        foreach (var clause in ruleSet.Clauses.OrderBy(c => c.Id.RuleNumber).ThenBy(c => c.Id.ClauseNumber))
        {
            var ruleId = clause.Id.RuleNumber;
            var clauseId = clause.Id.ClauseNumber;
            var safeName = CSharpIdentifierHelper.ToValidIdentifier(clause.Condition);
            var displayName = CodeGenerationHelper.EscapeStringLiteral(clause.Condition);

            parts.Add($"{indent}{indent}yield return new object[] {{ {ruleId}, {clauseId}, \"{safeName}\", \"{displayName}\" }};");
        }

        parts.Add($"{indent}}}");

        return string.Join("\n", parts);
    }

    private string GenerateTheoryTestMethod(ArchitectureRuleSet ruleSet, TestGenerationOptions options)
    {
        var indent = options.IndentString;
        var parts = new List<string>();

        if (options.IncludeComments)
        {
            parts.Add($"{indent}/// <summary>");
            parts.Add($"{indent}/// 执行 ADR-{ruleSet.AdrNumber:D3} 的所有条款测试");
            parts.Add($"{indent}/// </summary>");
            parts.Add($"{indent}/// <param name=\"ruleId\">规则编号</param>");
            parts.Add($"{indent}/// <param name=\"clauseId\">条款编号</param>");
            parts.Add($"{indent}/// <param name=\"safeName\">安全名称（用于标识）</param>");
            parts.Add($"{indent}/// <param name=\"displayName\">显示名称</param>");
        }

        parts.Add($"{indent}[Theory(DisplayName = \"ADR-{ruleSet.AdrNumber:D3} 条款执行测试\")]");
        parts.Add($"{indent}[MemberData(nameof(GetAllClausesData))]");
        parts.Add($"{indent}public void ExecuteClause(int ruleId, int clauseId, string safeName, string displayName)");
        parts.Add($"{indent}{{");

        if (options.IncludeExampleImplementation)
        {
            parts.Add(GenerateExampleImplementation(ruleSet, options, indent + indent));
        }
        else
        {
            parts.Add($"{indent}{indent}// TODO: 实现具体的测试逻辑");
            parts.Add($"{indent}{indent}throw new NotImplementedException($\"需要实现 Rule {{ruleId}} Clause {{clauseId}} 的测试逻辑\");");
        }

        parts.Add($"{indent}}}");

        return string.Join("\n", parts);
    }

    private string GenerateExampleImplementation(ArchitectureRuleSet ruleSet, TestGenerationOptions options, string baseIndent)
    {
        var parts = new List<string>();

        parts.Add($"{baseIndent}// 获取规则集和条款定义");
        parts.Add($"{baseIndent}var ruleSet = RuleSetRegistry.GetStrict({ruleSet.AdrNumber});");
        parts.Add($"{baseIndent}var clause = ruleSet.GetClause(ruleId, clauseId);");
        parts.Add($"{baseIndent}");
        parts.Add($"{baseIndent}// 验证条款存在");
        parts.Add($"{baseIndent}clause.Should().NotBeNull($\"Rule {{ruleId}} Clause {{clauseId}} 应该存在\");");
        parts.Add($"{baseIndent}");
        parts.Add($"{baseIndent}// 构建 RuleId");
        parts.Add($"{baseIndent}var ruleIdStr = $\"ADR-{ruleSet.AdrNumber:D3}_{{ruleId}}_{{clauseId}}\";");
        parts.Add($"{baseIndent}");
        parts.Add($"{baseIndent}// 根据执行类型执行不同的验证逻辑");
        parts.Add($"{baseIndent}switch (clause!.ExecutionType)");
        parts.Add($"{baseIndent}{{");
        parts.Add($"{baseIndent}    case ClauseExecutionType.Convention:");
        parts.Add($"{baseIndent}        // Convention 类型：使用 NetArchTest 进行架构约定检查");
        parts.Add($"{baseIndent}        ExecuteConventionTest(ruleIdStr, clause);");
        parts.Add($"{baseIndent}        break;");
        parts.Add($"{baseIndent}");
        parts.Add($"{baseIndent}    case ClauseExecutionType.StaticAnalysis:");
        parts.Add($"{baseIndent}        // StaticAnalysis 类型：需要 Roslyn Analyzer 支持");
        parts.Add($"{baseIndent}        // 这里可以标记为需要人工验证或跳过");
        parts.Add($"{baseIndent}        Console.WriteLine($\"Rule {{ruleId}} Clause {{clauseId}} 需要 Roslyn Analyzer 支持\");");
        parts.Add($"{baseIndent}        break;");
        parts.Add($"{baseIndent}");
        parts.Add($"{baseIndent}    case ClauseExecutionType.Documentation:");
        parts.Add($"{baseIndent}        // Documentation 类型：文档验证");
        parts.Add($"{baseIndent}        Console.WriteLine($\"Rule {{ruleId}} Clause {{clauseId}} 需要文档验证\");");
        parts.Add($"{baseIndent}        break;");
        parts.Add($"{baseIndent}");
        parts.Add($"{baseIndent}    case ClauseExecutionType.ManualReview:");
        parts.Add($"{baseIndent}        // ManualReview 类型：需要人工审查");
        parts.Add($"{baseIndent}        Console.WriteLine($\"Rule {{ruleId}} Clause {{clauseId}} 需要人工审查\");");
        parts.Add($"{baseIndent}        break;");
        parts.Add($"{baseIndent}");
        parts.Add($"{baseIndent}    case ClauseExecutionType.Runtime:");
        parts.Add($"{baseIndent}        // Runtime 类型：运行时验证");
        parts.Add($"{baseIndent}        Console.WriteLine($\"Rule {{ruleId}} Clause {{clauseId}} 需要运行时验证\");");
        parts.Add($"{baseIndent}        break;");
        parts.Add($"{baseIndent}");
        parts.Add($"{baseIndent}    default:");
        parts.Add($"{baseIndent}        throw new NotSupportedException($\"不支持的执行类型: {{clause.ExecutionType}}\");");
        parts.Add($"{baseIndent}}}");
        parts.Add($"{baseIndent}");
        parts.Add($"{baseIndent}// 验证测试已执行");
        parts.Add($"{baseIndent}// 注意：这是一个占位断言，实际测试应该有具体的验证逻辑");
        parts.Add($"{baseIndent}Assert.True(true, $\"Rule {{ruleId}} Clause {{clauseId}} ({{displayName}}) 已执行\");");
        parts.Add($"{baseIndent}");
        parts.Add($"{baseIndent}// 示例：添加具体的 NetArchTest 断言");
        parts.Add($"{baseIndent}// ExecuteConventionTest(ruleIdStr, clause);");
        parts.Add($"{baseIndent}");
        parts.Add($"{baseIndent}static void ExecuteConventionTest(string ruleId, ArchitectureClauseDefinition clause)");
        parts.Add($"{baseIndent}{{");
        parts.Add($"{baseIndent}    // TODO: 实现具体的 NetArchTest 断言");
        parts.Add($"{baseIndent}    // 示例：");
        parts.Add($"{baseIndent}    // var result = Types.InCurrentDomain()");
        parts.Add($"{baseIndent}    //     .That()");
        parts.Add($"{baseIndent}    //     .ResideInNamespace(\"YourNamespace\")");
        parts.Add($"{baseIndent}    //     .Should()");
        parts.Add($"{baseIndent}    //     .NotDependOnAny(\"ForbiddenNamespace\")");
        parts.Add($"{baseIndent}    //     .GetResult();");
        parts.Add($"{baseIndent}    //");
        parts.Add($"{baseIndent}    // result.IsSuccessful.Should().BeTrue(");
        parts.Add($"{baseIndent}    //     AssertionMessageBuilder.BuildFailureMessage(");
        parts.Add($"{baseIndent}    //         ruleId,");
        parts.Add($"{baseIndent}    //         clause.Condition,");
        parts.Add($"{baseIndent}    //         result.FailingTypeNames));");
        parts.Add($"{baseIndent}}}");

        return string.Join("\n", parts);
    }

    private string GenerateFactTestMethods(ArchitectureRuleSet ruleSet, TestGenerationOptions options)
    {
        var indent = options.IndentString;
        var parts = new List<string>();

        foreach (var clause in ruleSet.Clauses.OrderBy(c => c.Id.RuleNumber).ThenBy(c => c.Id.ClauseNumber))
        {
            var ruleId = clause.Id.RuleNumber;
            var clauseId = clause.Id.ClauseNumber;
            var safeName = CSharpIdentifierHelper.ToValidIdentifier(clause.Condition);
            var methodName = $"Rule{ruleId}_Clause{clauseId}_{safeName}";

            if (options.IncludeComments)
            {
                parts.Add($"{indent}/// <summary>");
                parts.Add($"{indent}/// ADR-{ruleSet.AdrNumber:D3}_Rule{ruleId}_Clause{clauseId}: {clause.Condition}");
                parts.Add($"{indent}/// </summary>");
            }

            parts.Add($"{indent}[Fact(DisplayName = \"ADR-{ruleSet.AdrNumber:D3}_{ruleId}_{clauseId}: {CodeGenerationHelper.EscapeStringLiteral(clause.Condition)}\")]");
            parts.Add($"{indent}public void {methodName}()");
            parts.Add($"{indent}{{");
            parts.Add($"{indent}{indent}// TODO: 实现 Rule {ruleId} Clause {clauseId} 的测试逻辑");
            parts.Add($"{indent}{indent}throw new NotImplementedException();");
            parts.Add($"{indent}}}");
            parts.Add("");
        }

        return string.Join("\n", parts);
    }
}
