namespace Zss.BilliardHall.Tests.ArchitectureTests.Specification.Generation;

/// <summary>
/// 生成器使用示例
/// 展示如何使用 ArchitectureTestGenerator 生成测试代码
/// </summary>
public sealed class GeneratorUsageExample_Tests
{
    [Fact(DisplayName = "示例：为 ADR-907 生成测试代码")]
    public void Example_Generate_Test_For_ADR907()
    {
        // 1. 创建生成器实例
        var generator = new ArchitectureTestGenerator();

        // 2. 获取 RuleSet（使用 ADR-907 作为示例）
        var ruleSet = RuleSetRegistry.GetStrict(907);

        // 3. 生成测试代码
        var result = generator.Generate(ruleSet);

        // 4. 验证生成结果
        result.Should().NotBeNull();
        result.ClassName.Should().Be("Adr907AutoGenerated_Tests");
        result.TestMethodCount.Should().BeGreaterThan(0);

        // 5. 输出生成的代码（用于查看）
        Console.WriteLine("=== 生成的测试类 ===");
        Console.WriteLine($"类名: {result.ClassName}");
        Console.WriteLine($"命名空间: {result.Namespace}");
        Console.WriteLine($"测试方法数: {result.TestMethodCount}");
        Console.WriteLine();
        Console.WriteLine("=== 源代码（前 50 行）===");
        var lines = result.SourceCode.Split('\n').Take(50);
        Console.WriteLine(string.Join('\n', lines));
    }

    [Fact(DisplayName = "示例：使用自定义选项生成测试代码")]
    public void Example_Generate_Test_With_Custom_Options()
    {
        // 1. 创建生成器
        var generator = new ArchitectureTestGenerator();

        // 2. 获取 RuleSet
        var ruleSet = RuleSetRegistry.GetStrict(907);

        // 3. 配置自定义选项
        var options = new TestGenerationOptions
        {
            Namespace = "MyProject.Tests.Architecture",
            TestClassSuffix = "_ArchTests",
            IncludeComments = true,
            IncludeExampleImplementation = true,
            UseTheoryPattern = true
        };

        // 4. 生成测试代码
        var result = generator.Generate(ruleSet, options);

        // 5. 验证自定义选项生效
        result.Namespace.Should().Be("MyProject.Tests.Architecture");
        result.ClassName.Should().Be("Adr907AutoGenerated_ArchTests");
        result.SourceCode.Should().Contain("namespace MyProject.Tests.Architecture;");
        result.SourceCode.Should().Contain("public sealed class Adr907AutoGenerated_ArchTests");
    }

    [Fact(DisplayName = "示例：生成简化的测试代码（不含示例实现）")]
    public void Example_Generate_Simplified_Test_Code()
    {
        // 1. 创建生成器
        var generator = new ArchitectureTestGenerator();

        // 2. 获取 RuleSet
        var ruleSet = RuleSetRegistry.GetStrict(907);

        // 3. 配置选项：不包含示例实现
        var options = new TestGenerationOptions
        {
            IncludeExampleImplementation = false,
            IncludeComments = true
        };

        // 4. 生成测试代码
        var result = generator.Generate(ruleSet, options);

        // 5. 验证生成的代码不包含示例实现
        result.SourceCode.Should().NotContain("RuleSetRegistry.GetStrict(907)");
        result.SourceCode.Should().Contain("// TODO: 实现具体的测试逻辑");
    }

    [Fact(DisplayName = "示例：验证生成的代码结构")]
    public void Example_Verify_Generated_Code_Structure()
    {
        // 生成测试代码
        var generator = new ArchitectureTestGenerator();
        var ruleSet = RuleSetRegistry.GetStrict(907);
        var result = generator.Generate(ruleSet);

        // 验证代码结构
        result.SourceCode.Should().Contain("namespace ");
        result.SourceCode.Should().Contain("public sealed class ");
        result.SourceCode.Should().Contain("public static IEnumerable<object[]> GetAllClausesData()");
        result.SourceCode.Should().Contain("[Theory(DisplayName = ");
        result.SourceCode.Should().Contain("[MemberData(nameof(GetAllClausesData))]");
        result.SourceCode.Should().Contain("public void ExecuteClause(");
    }

    [Fact(DisplayName = "示例：为自定义 RuleSet 生成测试代码")]
    public void Example_Generate_Test_For_Custom_RuleSet()
    {
        // 1. 创建自定义 RuleSet
        var ruleSet = new ArchitectureRuleSet(999);

        ruleSet.AddRule(
            1,
            "示例规则",
            DecisionLevel.Must,
            RuleSeverity.Governance,
            RuleScope.Test);

        ruleSet.AddClause(
            1,
            1,
            "条件：所有测试类必须有测试",
            "执行：使用 NetArchTest 验证",
            ClauseExecutionType.Convention);

        ruleSet.AddClause(
            1,
            2,
            "条件：测试类必须在 Tests 命名空间",
            "执行：使用静态分析验证",
            ClauseExecutionType.StaticAnalysis);

        // 2. 生成测试代码
        var generator = new ArchitectureTestGenerator();
        var result = generator.Generate(ruleSet);

        // 3. 验证生成结果
        result.ClassName.Should().Be("Adr999AutoGenerated_Tests");
        result.SourceCode.Should().Contain("ADR-999");

        // 验证包含两个条款的数据
        var yieldCount = Regex.Matches(result.SourceCode, @"yield return").Count;
        yieldCount.Should().Be(2);
    }
}
