@Host_HostAddress = http://localhost:5267

GET {{Host_HostAddress}}/weatherforecast/
Accept: application/json
###

POST {{Host_HostAddress}}/api/members
Content-Type: application/json

{
  "name": "John Doe",
  "email": "test@test.com"
}
###

POST {{Host_HostAddress}}/api/v2/members
Content-Type: application/json

{
  "name": "John Doe",
  "email": "test1111@test.com"
}
###

GET  {{Host_HostAddress}}/api/members/019c57f0-dacd-78c5-8df0-add5f9c870f3
Accept: application/json
###
