@Host_HostAddress = http://localhost:5267

GET {{Host_HostAddress}}/weatherforecast/
Accept: application/json
###

POST {{Host_HostAddress}}/api/members
Content-Type: application/json

{
  "name": "John Doe",
  "email": "test@test.com"
}
###
