namespace Zss.BilliardHall.Tests.ArchitectureTests.Specification.Generation.Tests;

/// <summary>
/// ArchitectureTestGenerator 集成测试
/// 使用真实的 RuleSet (ADR-907) 进行端到端测试
/// </summary>
public sealed class ArchitectureTestGenerator_IntegrationTests
{
    private readonly IArchitectureTestGenerator _generator;

    public ArchitectureTestGenerator_IntegrationTests()
    {
        _generator = new ArchitectureTestGenerator();
    }

    [Fact(DisplayName = "应该为 ADR-907 生成完整的测试代码")]
    public void Should_Generate_Complete_Test_Code_For_ADR907()
    {
        // Arrange
        var ruleSet = RuleSetRegistry.GetStrict(907);

        // Act
        var result = _generator.Generate(ruleSet);

        // Assert
        result.Should().NotBeNull();
        result.ClassName.Should().Be("Adr907AutoGenerated_Tests");
        result.Namespace.Should().Be("Zss.BilliardHall.Tests.ArchitectureTests.Generated");
        result.TestMethodCount.Should().Be(1); // Theory 模式
        result.SourceCode.Should().NotBeNullOrEmpty();
    }

    [Fact(DisplayName = "生成的代码应该包含所有 ADR-907 条款")]
    public void Generated_Code_Should_Include_All_ADR907_Clauses()
    {
        // Arrange
        var ruleSet = RuleSetRegistry.GetStrict(907);
        var expectedClauseCount = ruleSet.ClauseCount;

        // Act
        var result = _generator.Generate(ruleSet);

        // Assert
        var yieldCount = Regex.Matches(result.SourceCode, @"yield return").Count;
        yieldCount.Should().Be(expectedClauseCount, "应该为每个条款生成一个 yield return 语句");
    }

    [Fact(DisplayName = "生成的代码应该包含正确的 RuleId 格式")]
    public void Generated_Code_Should_Include_Correct_RuleId_Format()
    {
        // Arrange
        var ruleSet = RuleSetRegistry.GetStrict(907);

        // Act
        var result = _generator.Generate(ruleSet);

        // Assert
        result.SourceCode.Should().Contain("ADR-907");
        result.SourceCode.Should().Contain("var ruleIdStr = $\"ADR-907_{ruleId}_{clauseId}\";");
    }

    [Fact(DisplayName = "生成的代码应该包含 RuleSetRegistry 访问")]
    public void Generated_Code_Should_Include_RuleSetRegistry_Access()
    {
        // Arrange
        var ruleSet = RuleSetRegistry.GetStrict(907);

        // Act
        var result = _generator.Generate(ruleSet);

        // Assert
        result.SourceCode.Should().Contain("RuleSetRegistry.GetStrict(907)");
    }

    [Fact(DisplayName = "生成的代码应该包含执行类型的 switch 语句")]
    public void Generated_Code_Should_Include_ExecutionType_Switch()
    {
        // Arrange
        var ruleSet = RuleSetRegistry.GetStrict(907);

        // Act
        var result = _generator.Generate(ruleSet);

        // Assert
        result.SourceCode.Should().Contain("switch (clause!.ExecutionType)");
        result.SourceCode.Should().Contain("case ClauseExecutionType.Convention:");
        result.SourceCode.Should().Contain("case ClauseExecutionType.StaticAnalysis:");
        result.SourceCode.Should().Contain("case ClauseExecutionType.Documentation:");
        result.SourceCode.Should().Contain("case ClauseExecutionType.ManualReview:");
        result.SourceCode.Should().Contain("case ClauseExecutionType.Runtime:");
    }

    [Fact(DisplayName = "生成的代码应该包含 ExecuteConventionTest 辅助方法")]
    public void Generated_Code_Should_Include_ExecuteConventionTest_Helper()
    {
        // Arrange
        var ruleSet = RuleSetRegistry.GetStrict(907);

        // Act
        var result = _generator.Generate(ruleSet);

        // Assert
        result.SourceCode.Should().Contain("static void ExecuteConventionTest(string ruleId, ArchitectureClauseDefinition clause)");
        result.SourceCode.Should().Contain("// TODO: 实现具体的 NetArchTest 断言");
    }

    [Fact(DisplayName = "生成的代码应该使用统一的行尾")]
    public void Generated_Code_Should_Use_Consistent_Line_Endings()
    {
        // Arrange
        var ruleSet = RuleSetRegistry.GetStrict(907);

        // Act
        var result = _generator.Generate(ruleSet);

        // Assert
        result.SourceCode.Should().NotContain("\r\n");
        result.SourceCode.Should().NotContain("\r");
    }

    [Fact(DisplayName = "生成的代码应该验证有效性")]
    public void Generated_Code_Should_Pass_Validation()
    {
        // Arrange
        var ruleSet = RuleSetRegistry.GetStrict(907);

        // Act
        var result = _generator.Generate(ruleSet);

        // Assert
        var exception = Record.Exception(() => result.Validate());
        exception.Should().BeNull();
    }

    [Fact(DisplayName = "生成的代码应该包含详细的文档注释")]
    public void Generated_Code_Should_Include_Documentation_Comments()
    {
        // Arrange
        var ruleSet = RuleSetRegistry.GetStrict(907);

        // Act
        var result = _generator.Generate(ruleSet);

        // Assert
        result.SourceCode.Should().Contain("/// <summary>");
        result.SourceCode.Should().Contain("/// ADR-907 自动生成架构测试");
        result.SourceCode.Should().Contain("/// 此文件由 ArchitectureTestGenerator 自动生成");
    }

    [Fact(DisplayName = "生成的代码应该包含使用说明")]
    public void Generated_Code_Should_Include_Usage_Instructions()
    {
        // Arrange
        var ruleSet = RuleSetRegistry.GetStrict(907);

        // Act
        var result = _generator.Generate(ruleSet);

        // Assert
        result.SourceCode.Should().Contain("使用说明：");
        result.SourceCode.Should().Contain("此测试使用 Theory + MemberData 模式");
    }

    [Fact(DisplayName = "应该支持生成不包含示例实现的代码")]
    public void Should_Support_Generation_Without_Example_Implementation()
    {
        // Arrange
        var ruleSet = RuleSetRegistry.GetStrict(907);
        var options = new TestGenerationOptions { IncludeExampleImplementation = false };

        // Act
        var result = _generator.Generate(ruleSet, options);

        // Assert
        result.SourceCode.Should().NotContain("RuleSetRegistry.GetStrict(907)");
        result.SourceCode.Should().Contain("// TODO: 实现具体的测试逻辑");
    }

    [Fact(DisplayName = "应该支持生成不包含注释的代码")]
    public void Should_Support_Generation_Without_Comments()
    {
        // Arrange
        var ruleSet = RuleSetRegistry.GetStrict(907);
        var options = new TestGenerationOptions { IncludeComments = false };

        // Act
        var result = _generator.Generate(ruleSet, options);

        // Assert
        result.SourceCode.Should().NotContain("/// <summary>");
    }

    [Fact(DisplayName = "生成的代码应该包含所有必需的条款数据")]
    public void Generated_Code_Should_Include_All_Required_Clause_Data()
    {
        // Arrange
        var ruleSet = RuleSetRegistry.GetStrict(907);

        // Act
        var result = _generator.Generate(ruleSet);

        // Assert
        // 验证每个条款都有对应的测试数据
        foreach (var clause in ruleSet.Clauses)
        {
            var ruleId = clause.Id.RuleNumber;
            var clauseId = clause.Id.ClauseNumber;
            
            // 应该包含条款数据
            result.SourceCode.Should().Contain($"{{ {ruleId}, {clauseId},");
        }
    }
}
