

namespace Zss.BilliardHall.Tests.ArchitectureTests.Specification.RuleSets.ADR907;

public sealed class Adr907AutoGenerated_Tests
{
    #region 辅助方法

    private void ExecuteClause(int ruleId, int clauseId, string clauseName)
    {
        // 尝试查找执行绑定
        var binding = Adr907ExecutionBindings.Lookup(ruleId, clauseId);
        if (binding != null)
        {
            // 如果绑定存在
            Console.WriteLine($"执行绑定: {binding.HandlerKey}");
        }
        else
        {
            // 默认执行 ArchitectureTests
            Console.WriteLine($"默认执行 ArchitectureTests: Rule {ruleId} Clause {clauseId} - {clauseName}");
        }
    }

    private void RunRuleClause(Adr907Definitions.RuleInfo rule, Adr907Definitions.RuleInfo ruleInfo, ClauseSpec clause)
    {
        ExecuteClause(rule.RuleId, clause.ClauseId, clause.Name);
    }

    #endregion

    #region 自动生成测试方法

    static Adr907AutoGenerated_Tests()
    {
        // 动态生成 Fact 方法
        foreach (var rule in Adr907Definitions.AllRules)
        {
            foreach (var clause in rule.Clauses)
            {
                // 这里用 xUnit Dynamic Test 不直接生成方法体，而是在测试运行时遍历执行
                Console.WriteLine($"测试生成: ADR-907_Rule{rule.RuleId}_Clause{clause.ClauseId} - {clause.Name}");
            }
        }
    }

    [Theory(DisplayName = "ADR-907 自动生成条款测试")]
    [MemberData(nameof(AllRuleClauses))]
    public void RunAllClauses(int ruleId, int clauseId, string clauseName)
    {
        ExecuteClause(ruleId, clauseId, clauseName);
    }

    public static IEnumerable<object[]> AllRuleClauses()
    {
        foreach (var rule in Adr907Definitions.AllRules)
        {
            foreach (var clause in rule.Clauses)
            {
                yield return new object[] { rule.RuleId, clause.ClauseId, clause.Name };
            }
        }
    }

    #endregion
}

