namespace Zss.BilliardHall.Tests.ArchitectureTests.Specification.RuleSets.ADR907.tests;

/// <summary>
/// ADR-907 Rule 3: 最小断言语义规范
/// 验证测试的断言质量和语义规范
/// </summary>
public sealed class Adr907Rule3_Tests
{
    private readonly Adr907RuleSet _ruleSet = new();
    private ArchitectureRuleSet _adr907RuleSet => _ruleSet.Define();

    [Fact(DisplayName = "ADR-907_3_1: 每个测试类至少包含1个有效断言")]
    public void ADR_907_3_1_最小断言数量()
    {
        var clause = _adr907RuleSet.GetClause(3, 1);
        clause.Should().NotBeNull("Clause 3.1 必须存在");
        
        var testAssembly = typeof(Adr907Rule3_Tests).Assembly;
        var testTypes = Adr907TestHelpers.GetAdrTestTypes(testAssembly)
            .Where(t => !IsKnownPlaceholder(t))
            .Where(t => t != typeof(Adr907Rule3_Tests))  // 排除当前类
            .ToList();
        
        var violations = FindTestClassesWithoutAssertions(testTypes);
        
        Adr907TestHelpers.AssertNoViolations(
            "ADR-907_3_1",
            "每个测试类必须至少包含一个有效断言",
            violations,
            new[] { 
                "为测试类添加有意义的测试方法",
                "确保测试方法包含实际的断言"
            });
    }

    [Fact(DisplayName = "ADR-907_3_2: 每个测试方法只能映射一个 ADR 子规则")]
    public void ADR_907_3_2_单一职责()
    {
        var clause = _adr907RuleSet.GetClause(3, 2);
        clause.Should().NotBeNull("Clause 3.2 必须存在");
        
        var testType = typeof(Adr907Rule1_Tests);
        var testMethods = Adr907TestHelpers.GetRuleClauseTestMethods(testType);
        
        var violations = FindMethodsWithMultipleRuleClauses(testMethods);
        
        Adr907TestHelpers.AssertNoViolations(
            "ADR-907_3_2",
            "每个测试方法只能映射一个 ADR 子规则",
            violations,
            new[] { 
                "拆分测试方法，每个方法只测试一个子规则",
                "使用 ADR_XXX_Rule_Clause_描述 格式命名"
            });
    }

    [Fact(DisplayName = "ADR-907_3_3: 所有断言失败信息必须可反向溯源到 ADR")]
    public void ADR_907_3_3_可溯源失败()
    {
        var clause = _adr907RuleSet.GetClause(3, 3);
        clause.Should().NotBeNull("Clause 3.3 必须存在");
        
        var sourceFile = Adr907TestHelpers.GetCurrentTestFilePath();
        if (sourceFile == null || !File.Exists(sourceFile))
        {
            return;
        }
        
        var usesBuilder = Adr907TestHelpers.FileContainsPattern(sourceFile, "AssertionMessageBuilder");
        var hasRuleIds = Adr907TestHelpers.FileMatchesRegex(sourceFile, @"ADR-\d{3}_\d+_\d+");
        
        (usesBuilder || hasRuleIds).Should().BeTrue(
            AssertionMessageBuilder.Build(
                "ADR-907_3_3",
                "测试必须使用可溯源的断言消息",
                "未检测到 AssertionMessageBuilder 或 RuleId 格式",
                new[] { 
                    "使用 AssertionMessageBuilder 构建断言消息",
                    "在断言消息中包含 ADR-XXX_Y_Z 格式的 RuleId",
                    "提供修复建议和文档引用"
                },
                "docs/adr/ADR-907.md"));
    }

    [Fact(DisplayName = "ADR-907_3_4: 禁止形式化断言")]
    public void ADR_907_3_4_禁止形式化()
    {
        var clause = _adr907RuleSet.GetClause(3, 4);
        clause.Should().NotBeNull("Clause 3.4 必须存在");
        
        // 这是一个软性检查，检测常见的形式化断言模式
        var sourceFile = Adr907TestHelpers.GetCurrentTestFilePath();
        if (sourceFile == null || !File.Exists(sourceFile))
        {
            return;
        }
        
        // 注意：这是启发式检查，可能有误报，所以只记录不强制失败
        var formalPatterns = new[]
        {
            @"\.Should\(\)\.BeTrue\(\s*\)",
            @"\.BeTrue\(true\)",
            @"\.BeFalse\(false\)",
            @"Assert\.True\(true\)",
            @"Assert\.False\(false\)"
        };
        
        foreach (var pattern in formalPatterns)
        {
            if (Adr907TestHelpers.FileMatchesRegex(sourceFile, pattern))
            {
                // 只记录，不强制失败
                Console.WriteLine($"ADR-907_3_4 警告：检测到可能的形式化断言模式: {pattern}");
            }
        }
    }

    #region 私有辅助方法

    private bool IsKnownPlaceholder(Type type)
    {
        var knownPlaceholders = new HashSet<string>
        {
            "Adr907AutoGenerated_Tests",
            "Adr907_Tests",
            "Adr907Auto_Tests"
        };
        
        return knownPlaceholders.Contains(type.Name);
    }

    private List<string> FindTestClassesWithoutAssertions(List<Type> testTypes)
    {
        var violations = new List<string>();
        
        foreach (var testType in testTypes)
        {
            var testMethods = Adr907TestHelpers.GetTestMethods(testType);
            
            if (testMethods.Count == 0)
            {
                violations.Add($"{testType.FullName}: 没有任何测试方法");
                continue;
            }
            
            var emptyMethods = testMethods.Count(m => Adr907TestHelpers.IsEmptyOrTooSmall(m));
            
            if (emptyMethods == testMethods.Count)
            {
                violations.Add($"{testType.FullName}: 所有 {testMethods.Count} 个测试方法都是空的或过小");
            }
        }
        
        return violations;
    }

    private List<string> FindMethodsWithMultipleRuleClauses(List<MethodInfo> testMethods)
    {
        var violations = new List<string>();
        
        foreach (var method in testMethods)
        {
            var matches = Regex.Matches(method.Name, @"_(\d+)_(\d+)_");
            if (matches.Count > 1)
            {
                violations.Add($"{method.Name}: 包含 {matches.Count} 个 Rule_Clause 组合");
            }
        }
        
        return violations;
    }

    #endregion
}
