global using System;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Linq;
global using System.Text.RegularExpressions;
global using Zss.BilliardHall.Specification.Index;
global using Zss.BilliardHall.Specification.Rules;
global using Zss.BilliardHall.Specification.Language.RuleIdLanguage;
global using Zss.BilliardHall.Specification.Language.DecisionLanguage;
