<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Platform\Platform.csproj"/>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="WolverineFx.Http"/>
    <PackageReference Include="WolverineFx.Marten"/>
    <PackageReference Include="Marten"/>
    <PackageReference Include="Marten.AspNetCore"/>
    <PackageReference Include="WolverineFx.Http.FluentValidation"/>
    <PackageReference Include="Microsoft.Extensions.Options"/>
  </ItemGroup>
</Project>
